spring:
  application:
      name: MicroservicioWoahoAdmin
  datasource:
     password: 
     testWhileIdle: 'true'
     url: jdbc:postgresql://198.54.123.142:5432/woaho
     username: woaho
     validationQuery: SELECT 1
  jpa:
     hibernate:
       ddl-auto: update
       naming:
         implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
         physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
     show-sql: 'true'
server:
  port: 8083
  servlet:
    context-path: /woahoAdmin
    multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://10.11.6.47:8761/eureka}
  instance:
    preferIpAddress: true
    
parametracion-adicional:
  appid: '0942319e-1677-4480-8992-a96e3882f7c7'
  restKey: 'Basic MTJiZjhkNmUtMTc0Ni00OTU5LWJmNDgtOTA0NDVjZmI5N2U3'
  directorio: 'E:\archivos'